### ISSUE TITLE
how to get the pretrained model

### ISSUE THREAD

**Issue by lazycg** [qymeng94/DSR#3]
HI,
I want to train this greate work,but got some bug.how can i get the "./checkpoint/CIFAR10DVS/vgg.vgg11_if./checkpoint.txt" file?

**Comment by qymeng94** [comment]
Thank you for following our work! 
For your question, I think that making args.name='checkpoint', rather than './checkpoint', will work.

Let me give an example of our naming system. If you are training dvs-cifar10 with the vgg.vgg11_if model and setting args.name='_checkpoint', the code will generate three files in the folder ./checkpoint/CIFAR10DVS, namely "vgg.vgg11_if_checkpoint.txt", "vgg.vgg11_if_checkpoint.pth", and "vgg.vgg11_if_checkpoint_best.pth". The txt file shows the lr, loss, and accuracy for each epoch.
So you can actually set args.name='' to make the name of output files clean.
